import { newId, type CvData } from "@/lib/cv/schema";

export function createSampleCv(): CvData {
  return {
    title: "My CV",
    templateId: "ats-one-column",
    personalInfo: {
      fullName: "Pich Chan Thorn",
      headline: "Hello World",
      email: "pich_chanthorn@pp.bbu.edu.kh",
      phone: "0973100485",
      location: "Phnom Penh, Cambodia",
      summary: "",
      links: [
        { id: newId(), label: "LinkedIn", url: "linkedin.com/in/pichchanthorn" },
        { id: newId(), label: "Portfolio", url: "pichchanthorn.me" },
      ],
    },
    experience: [
      {
        id: newId(),
        company: "Haystack Solutions",
        role: "Data Entry Specialist",
        location: "",
        startDate: "2026-05",
        endDate: "",
        isCurrent: true,
        bullets: [
          "Promoted from intern to full-time Data Entry Specialist",
          "Performing data entry, validation, and quality checking tasks",
          "Ensuring data accuracy and consistency",
        ],
      },
      {
        id: newId(),
        company: "Haystack Solutions",
        role: "Data Entry Specialist (Internship)",
        location: "Phnom Penh, Cambodia",
        startDate: "2026-01",
        endDate: "2026-04",
        isCurrent: false,
        bullets: [
          "Worked on-site as a Data Entry Specialist Intern",
          "Supported data entry, validation, and quality checking tasks",
          "Completed assigned workflows using an annotation/data processing platform",
          "Followed project guidelines and maintained accuracy and consistency",
          "Collaborated with the team to deliver tasks on time",
        ],
      },
      {
        id: newId(),
        company: "PCTN",
        role: "Founder & CEO",
        location: "Remote, Cambodia",
        startDate: "2020-01",
        endDate: "",
        isCurrent: true,
        bullets: [
          "Founded PCTN in 2020 as a small creative and tech-focused group centered on learning and sharing knowledge in web development, UI/UX design, and digital creativity",
          "Grew PCTN into a community where members collaborate on tech projects and build practical digital skills",
          "Currently leading brand development, content direction, and community coordination to expand PCTN into a recognized digital innovation group",
        ],
      },
    ],
    education: [
      {
        id: newId(),
        institution: "Build Bright University",
        degree: "Bachelor's Degree",
        fieldOfStudy: "Information Technology",
        location: "Phnom Penh, Cambodia",
        startDate: "2024-10",
        endDate: "2028-10",
        isCurrent: false,
        description: "",
      },
      {
        id: newId(),
        institution: "CAMBODIA-ASEAN International Institute",
        degree: "Foundation English Program",
        fieldOfStudy: "English Language and Communication",
        location: "",
        startDate: "2024-10",
        endDate: "2024-12",
        isCurrent: false,
        description: "",
      },
      {
        id: newId(),
        institution: "Svay Rieng High School",
        degree: "General Education",
        fieldOfStudy: "Academic Program",
        location: "",
        startDate: "2018-01",
        endDate: "2024-12",
        isCurrent: false,
        description: "",
      },
      {
        id: newId(),
        institution: "Johnson International School",
        degree: "High School Diploma",
        fieldOfStudy: "Chinese Language and General Education",
        location: "",
        startDate: "2020",
        endDate: "2022",
        isCurrent: false,
        description: "",
      },
    ],
    skills: [
      { id: newId(), name: "HTML", groupName: "Languages" },
      { id: newId(), name: "CSS", groupName: "Languages" },
      { id: newId(), name: "JavaScript", groupName: "Languages" },
      { id: newId(), name: "PHP", groupName: "Languages" },
      { id: newId(), name: "MySQL", groupName: "Databases" },
      { id: newId(), name: "Git", groupName: "Tools" },
      { id: newId(), name: "Figma", groupName: "Tools" },
      { id: newId(), name: "Data Entry", groupName: "Other" },
    ],
    projects: [],
    languages: [],
    certifications: [
      { id: newId(), name: "Play It Safe: Manage Security Risks", issuer: "", issueDate: "", credentialUrl: "" },
      { id: newId(), name: "Junior Cybersecurity Analyst Career Path", issuer: "", issueDate: "", credentialUrl: "" },
      { id: newId(), name: "Certificate of Achievement - General Knowledge Cambodia", issuer: "", issueDate: "", credentialUrl: "" },
      { id: newId(), name: "Foundations of Cybersecurity", issuer: "", issueDate: "", credentialUrl: "" },
      { id: newId(), name: "Certificate of Academic Excellence", issuer: "", issueDate: "", credentialUrl: "" },
    ],
  };
}
